services:
  - type: web
    name: mp3-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI

        value: mongodb+srv://chensy010227_db_user:f9Ijb1wEw5eZwtZT@cluster0.4hturbd.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
